import getListings from "./actions/GetListings";
import { IListingParams } from "./actions/GetListings";

import getCurrentUser from "./actions/GetCurrentUser";
import ListingsList from "./components/listingElements/ListingsList";
import Wrapper from "./components/uiElements/Wrapper";
import PageHeading from "./components/uiElements/PageHeading";
import EmptyList from "./components/uiElements/EmptyList";

interface HomeProps {
  searchParams: IListingParams;
}

export const metadata = (searchParams: IListingParams) => {
  let title = "Rent or book great properties";
  if (searchParams.category) {
    title = `Listings by ${searchParams.category}`;
  } else if (searchParams.search) {
    title = `Listings by '${searchParams.search}' query`;
  }

  return {
    title,
    description: "Generated by create next app",
  };
};

const Home = async ({ searchParams }: HomeProps) => {
  const listings = await getListings(searchParams);
  const currentUser = await getCurrentUser();

  if (!listings?.length)
    return (
      <EmptyList
        title="No results"
        subtitle="There are no properties to display at the moment."
      />
    );

  return (
    <main className="main-page">
      <Wrapper>
        {searchParams.category && (
          <PageHeading
            title={`Results by '${searchParams.category}' category`}
            subtitle="Browse listings in the selected category"
          />
        )}
        {searchParams.search && (
          <PageHeading
            title={`Results by '${searchParams.search}' query`}
            subtitle="Browse listings matching the search query"
          />
        )}

        <ListingsList currentUser={currentUser} listings={listings} />
      </Wrapper>
    </main>
  );
};

export default Home;
